### PR TITLE
Patrick/html/lab02

### PR DESCRIPTION
**Pull request by PatrickCoteWurzler**
lab02 ready for grading

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Check the mobile version of your page. I'm seeing a number of elements not resizing for the smaller screen size. See if you can fix that!

**Comment by burrowdown** [comment]
Something terrible and unknowable has happened on this branch. Patrick will open a new one from a new, clean branch when the changes are ready.

**Comment by burrowdown** [comment]
I CLOSED THE WRONG ONE, TOTALLY MY FAULT, I'M SORRY!!

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
You fixed the elements that weren't resizing on mobile view, thanks!

We don't, however, have any layout distinction between mobile and desktop views. Spend a few moments navigating the page on desktop view, and think about how you could change that layout to be more naturally-readable.

**Review by iammattwalsh — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
