### PR TITLE
patrick lab03 push

### PR DESCRIPTION
**Pull request by PatrickCoteWurzler**

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
You're almost there, but I found 2 issues. I'll tell you one of them: you forgot to calculate the number of pennies. Check your output to figure out the other issue please!

**Comment by PatrickCoteWurzler** [comment]
Hey Matt, Checking to see if this works to communicate that I have made the requested changes.

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Very close! You have a typo in line 6 that's causing issues though, and what looks like another typo that's resulting in incorrect results. Let me know if you don't find the second one!

**Review by iammattwalsh — APPROVED** [review]
This is great, thanks for the update!

**Comment by burrowdown** [comment]
Hey @PatrickCoteWurzler Can you clean up this branch so that it only has lab 3 on it? It will cause merge conflicts if I merge this with the duplicate files. When you're done the "Files changed" tab should only show lab 3.

**Comment by PatrickCoteWurzler** [comment]
Hey Danny, I cleaned it up so it should be good to merge

**Pull request merged**
