### PR TITLE
Lab 6 v1 and v2 added

### PR DESCRIPTION
**Pull request by NSJen**

### CODE REVIEW

**Review by chapman311 — CHANGES_REQUESTED** [review]
Nice job Jen. A few things that caught my eye, one matters and the other two won't necessarily change how the code functions, but could improve it's logic structure. 

- The lab askes for ticket numbers to be between 0 and 99. My first ticket had a 100 on it. I would look at `random.randint()` and be sure it is being used correctly. *(You can hover your mouse over `randint` in VS Code to get more info.)
- The naming of winning ticket and your ticket seems to be reversed. Not a big deal.
- I am seeing repeating code for the ticket number selections and the index position checking. Again, not going to change the output, but I thought you might like another crack at it. 

Nice job, just a few minor things. Let me know if you have any questions.

**Comment by NSJen** [comment]
I fixed the code for the random pull and made the overall code a bit more efficient in both files.

**Review by chapman311 — CHANGES_REQUESTED** [review]
Thank you for making the change to `random.randint(1,99)` for the ticket numbers.

Also, thank you for attempting to make your code more concise within the `num_matches` function. Unfortunately it looks like the nested for-loops are producing multiple matches across the winning ticket for each number in the ticket. Also the use of `enumerate()` could be helpful here, but is unnecessary to use if you are not going to use the `i` variable produced by it. 

Finally, your ROI in version 2 looks to be a bit off, maybe an inverse of the expected answer? I am not so strict on this output because it can be confusing to get 'right'.

You'll be good to go if you focus on repairing the 'num_matches' function to get the correct number of matches for 'ticket' compared with 'winning_ticket'. Use some 'print()' 's to see what it is returning. :)

**Review by chapman311 — CHANGES_REQUESTED** [review]
Hi Jen. Thank you for making the changes. Unfortunately the code is giving numbers outside of the acceptable range for final output. 

I might start with the `num_matches` function, use of the `iterations` variable name multiple times might be messing things up? 

I am also not seeing where the `win_amounts` dictionary is applying the correct win value to the total. Please thoroughly test the code before re-submission.

**Review by chapman311 — APPROVED** [review]
Code looks great! Awesome job. A new-to-me use of the while-loop that allows for `iterations` to equal 0. Very cool!

**Pull request merged**
