### PR TITLE
Added lab 10

### PR DESCRIPTION
**Pull request by NSJen**
Lab 10 and Lab 10 v2

### CODE REVIEW

**Comment by NSJen** [comment]
I deleted the wrong version. Version 3 meets the requirements, it just also decrypts.

**Comment by NSJen** [comment]
Just kidding. Both extra versions seem to be gone now.

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
This is really close! I'd like to see it able to handle spaces (if they're in the input string, include them in the correct position in the output string).

That's all I need to approve, but I do have an extra challenge I think you can handle: see if you can make it also return capital letters in the correct position after rotation. This is optional, but is nice practice!

**Review by iammattwalsh — APPROVED** [review]
Thanks for the changes! You're completely correct that including capitals and spaces makes this already-weak encryption even less secure, but I appreciate you tackling the extra challenge!

**Pull request merged**
