### PR TITLE
Lab 11

### PR DESCRIPTION
**Pull request by NSJen**

### CODE REVIEW

**Review by chapman311 — CHANGES_REQUESTED** [review]
This lab requires that a body of text, as a `.txt`, is loaded in by the python file for interpretation.  It looks like the made up version 2 of this lab achieves this. Please only submit the required lab 11 solution. It may be beneficial to hold off on completing this lab until it is assigned. Nice work though, it looks good.

**Review by chapman311 — APPROVED** [review]
Awesome job Jen. Thank you for making the requested changes.  Code looks great.

**Comment by NSJen** [comment]
I made a change after it was approved. I'm not sure how that shows up on that end.

**Comment by burrowdown** [comment]
@NSJen You can keep making pushes to the branch all the way up until it is merged, and those changes will show up in your files once they are merged to main. What you do to your labs after they are graded is your business, so even if you screwed them up somehow you've already gotten credit for the lab so you're good to go. :)

**Pull request merged**
