### PR TITLE
Added Lab1

### PR DESCRIPTION
**Pull request by NSJen**

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Check your output on this; the converted values aren't accurate. Also please check the lab instructions, specifically this part:

> But instead of filling out that matrix, and checking for each pair of units (if from_units == 'mi' and to_units == 'km'), **we can just convert any unit to meters, then convert the distance in meters to any other unit.**

In the revised version, please add the ability to convert _from_ km (currently you can only convert _to_ km).

Thank you!

**Comment by NSJen** [comment]
I did the push but the pull request doesn't show my request. km was available functionally, I added it to the input request. 

Jen

**Comment by NSJen** [comment]
My push errored. The update is here now. 

Thanks!

**Review by iammattwalsh — APPROVED** [review]
Thanks for the revision! It's much cleaner now, and works great!

**Review by pjz987 — APPROVED** [review]

**Pull request merged**
