### PR TITLE
lab10.py final

### PR DESCRIPTION
**Pull request by PatrickCoteWurzler**
lab10 version 1 complete

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Nice job so far; this is very close to finished. I'd like to see the output a little cleaner (you have some test prints in your for loop). There's a bigger issue though: your code can't handle spaces at the moment. See if you can fix that!

**Comment by PatrickCoteWurzler** [comment]
Good Morning Matt. I have made the requested changes. Please take a look and make sure you are happy with it. Thanks!

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Thanks for the changes! This is almost there, but it should also be able to handle capitalization (and preferably punctuation) without crashing. You can choose to include them in place in the output string if you'd like, but that's not strictly necessary.  Thanks!

**Comment by PatrickCoteWurzler** [comment]
Hey Matt, I have completed the required changes. Let me know if you run into any issues.

**Review by iammattwalsh — APPROVED** [review]
Thanks for the changes, this is great!

**Pull request merged**
