### PR TITLE
lab 8 still working not complete

### PR DESCRIPTION
**Pull request by Krystah**
Please pull this branch. I'm still working the labs just needed to push the branch so I could pull and work on another. Thank you! : )

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Looks good so far, but the output isn't as expected. The CC# given on the lab instructions should return valid, but it does not. There are 2 issues causing this, and I think 1 of them is based on misunderstanding the instructions:

> 6. Sum all values.

This is somewhat vague, but in this case "all values" isn't meant to include the check digit. 

You'll likely spot the other issue if you look at your output carefully.

When lab instructions give a valid input and associated output, please make sure your lab can replicate that output. 🙂

**Comment by Krystah** [comment]
Thanks, Matt! The number provided in the lab validates now. I saw in step 6 where I needed to remove the checked digit. I updated step 8 to verify the 0 index in the check_digits list since there will always only ever be one number pop'd to that list. That seemed to fix the error.

**Review by iammattwalsh — APPROVED** [review]
Nice work! This returns valid/invalid as expected now.

I have a tip though: if you're storing a single number (as with your check_digit variable), it usually makes more sense to avoid putting it in a list and instead save it to one of the number types (int or float). That will make accessing it slightly easier (no `[0]` needed), is marginally more resource-efficient, in your case would save 2 lines of code, and is the "right" way to do it.

You have a line of code in there that already assigns it as I would expect, but you don't end up using that variable later (look at line 11 if you're interested). If you want to go over any of this in a breakout, let me know.

What you did totally works though, so this is approved!

**Comment by burrowdown** [comment]
hey @Krystah can you clean up this branch? It wound up with a lot of extra files on it

**Pull request merged**
