### PR TITLE
Lab 2

### PR DESCRIPTION
**Pull request by Velshaun**

### CODE REVIEW

**Comment by chapman311** [comment]
Please refrain from naming the git branch '.py', it is not a python file, it is just a branch name. :)

**Comment by Velshaun** [comment]
Ok!

**Review by chapman311 — CHANGES_REQUESTED** [review]
First part of Lab 2 is missing. 

Please revise the '02lab.py' to include the version 1 code, above the version 2 code; with comments in the code for which is which. 

Preferably, there can be a separate file for each version of the lab: '02lab_ver1.py' and '02lab_ver2.py'

**Review by chapman311 — APPROVED** [review]
Thanks for making the changes! Code looks great.

**Comment by Velshaun** [comment]
Thanks!

**Review by pjz987 — APPROVED** [review]

**Pull request merged**
