### PR TITLE
lab04 commit with lab2.1 and lab05

### PR DESCRIPTION
**Pull request by PatrickCoteWurzler**
I forgot to add branches before moving onto other labs. will not do this in the future

### CODE REVIEW

**Review by chapman311 — CHANGES_REQUESTED** [review]
Lab 4 labs found. Please use a different naming convention for your files. 
lab04_ver1.py for version 1
lab04_ver2.py for version 2

lab04.1.py is the file that was graded. A few errors were found. Input is only asking for numbers 0-99, even though I can see that the code's logic handles numbers 0-999, as the Lab 4 Version 2 requires. Entering the number 19 results in a `KeyError`. Entering 0 results in a `KeyError`.

The same errors are being produced in Version 1. Please go back through the code and thoroughly test before re-submitting.

**Comment by chapman311** [comment]
Please let me know when this lab is complete so it can be graded.

**Comment by PatrickCoteWurzler** [comment]
Hey Mitch, I seem to have solved my key error issues. Just needed some time away from it to figure it out. Please take a look and let me know if I missed anything else. Thanks!

**Review by chapman311 — CHANGES_REQUESTED** [review]
Pat, I ran into a few issues:
The 'lab04.py' file, which I am assuming is version 1 of the lab, gives many `KeyError`s. Please review this file. 
The 'lab4.1.py' file threw a `KeyError` when I put in 100. 
Please throughouly test your code before resubmitting.  Please ask for help if needed.

**Comment by PatrickCoteWurzler** [comment]
Hey! I made the changes we talked about yesterday and tested until I was comfortable. Hopefully both versions work as they should for you.

**Review by chapman311 — CHANGES_REQUESTED** [review]
Patrick, unfortunately I ran into a few issues still. Remember this list of errors is likely not extensive and it is also possible that you may generate new errors as you work on the code. 

This is what I ran into:

- Version 1 and 2, entering 90 results in an output of 'nintyzero'.
- Version 2, entering 110 results in an output of 'one hundredeleven'.
- Version 2, entering 900 results in  a `KeyError`.

**Review by chapman311 — APPROVED** [review]
Great job on working through the errors on the lab. All outputs look good now! Thank you for removing the extra files from the branch as well. Good work!

**Review by pjz987 — APPROVED** [review]

**Pull request merged**
