### PR TITLE
Tony/python/lab05

### PR DESCRIPTION
**Pull request by webavant**

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Nice work on version 1!


Version 2 has a couple issues. Note that version 2 is optional, so you're welcome to remove it from the PR if you'd rather do that than correct it. I'd love to see it working though!

- Instead of keeping 2 running totals, try evaluating the aces to see which value is preferred.
- There's an issue with your "card value" output in some circumstances. Input all aces and check your output to spot the problem.

**Comment by webavant** [comment]
I prematurely requested a re-review.  I still need to modify it to properly handle more than one ace. I took your advice of keeping only one running total, but now I'm wondering if I can solve this with better/simple math. I'll submit another change later.

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Thanks for the update! Version 2 is close, but not quite there yet. I noticed 3 issues, listed from most important to least important:

1.  It still isn't handling aces quite right. For example, try entering "10", then "a". I would expect a blackjack, but "Hit" is printed.
2. "Stay" doesn't end the app. I'm not sure I would consider this a critical issue, but it is - to me at least - unexpected behavior.
3. This is very minor, but a running total of the player's score would be useful for someone using this app.

Issues 2 & 3 are minor enough that I will approve if they are unchanged, but issue 1 is a show-stopper as far as version 2 is concerned. You'll need to rethink how that is handled, and make sure you consider cases where an ace's value may change (e.g. if you were to draw a 3 and an ace, the ace would be worth 11 points, but if you were to draw an 8 next, the ace would now be worth 1 point to avoid busting).

Your translate function is a clever use of try/except - nice work!

**Comment by webavant** [comment]
1. Thanks for testing! I clearly didn't test enough. Sorry! :(
2. I expect that high-rollers and card counters will sometimes want to keep hitting.
3. It's certainly useful! I considered how to display the total, considering the ambiguous value of aces, then it seemed like I'd need to consult the official rules, so I just nixed it altogether.

**Comment by webavant** [comment]
I think you will find this satisfactory!

1. FIXED - `range(1, aces)` was excluding the case of having only a single ace. Updated to `range(0, aces)`.
2. UNCHANGED - Sometimes I want to hit even when the odds are against me. 
3. FIXED - It will now print the current lowest score, or 21.

I hope I put enough thought into this to save you any more time testing it!

**Review by iammattwalsh — APPROVED** [review]
Thanks for the updates! I really appreciate the well-commented code, and the emojis made me laugh. Nice work! 

Thanks for taking the time to read the feedback and respond, including declining one of my optional suggestions. I appreciate the dialog and demonstration that where your code behaved differently than I expected, it was an intentional decision rather than an oversight. Keep it up!

**Review by pjz987 — APPROVED** [review]

**Pull request merged**
