### PR TITLE
Mileidy/python/lab13

### PR DESCRIPTION
**Pull request by mileidy1**

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
This is close, but it's missing a way to display the transaction log! It looks like you wrote the method, but didn't add it to your REPL.

**Comment by mileidy1** [comment]
Ahh okay i still have it open i felt like i was missing something but im so
tired i couldn’t figure it out 🤣

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Almost there, but it's still missing interest transactions on the transaction log. Can you add that please? Thanks!

**Comment by mileidy1** [comment]
hey matt i updated it and added in the part where it prints out the interest and made some more tweaks !

**Pull request merged**
