### PR TITLE
Faith/python/lab17

### PR DESCRIPTION
**Pull request by Faebaeee**

### CODE REVIEW

**Review by chapman311 — COMMENTED** [review]
Great work! Everything looks good. Short and sweet! :)

**Review by chapman311 — CHANGES_REQUESTED** [review]
On second look, I am now seeing that there are all of your Django files for your minicapstone in this folder. Can you clean up the branch and resubmit with only Lab 17 please?

**Comment by Faebaeee** [comment]
I will try my best, I'm nit to sure of way to do it but i will get it done :)

**Comment by chapman311** [comment]
Hi Faith. It appears there are still 4 `.png` files, related to your capstone, still on this branch. Please reach out if you need assistance with removing these.

**Comment by Faebaeee** [comment]
Hey i think i got rid of the rest of the stragglers. Let me know if it still doesn't look right

**Review by chapman311 — APPROVED** [review]
Okay. Good to go. Thank you for removing all those files!

**Pull request merged**
