### PR TITLE
Patrick/python/lab05

### PR DESCRIPTION
**Pull request by PatrickCoteWurzler**

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
This is a solid start, but it's missing a couple things: there's a card that doesn't work, and your code will only respond with "hit" or "stay" when there are a couple more options. Nice work so far!

**Comment by PatrickCoteWurzler** [comment]
Hey Matt, I made the requested changes to lab05. Please take a look when you have time. Thanks!

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Nice work so far, but I'd like to see 2 more changes:

1. When displaying results, can you show the total card value rather than just the individual cards (e.g. 15 if the user has an 8, a 4, and a 3).
2. When I get blackjack or bust, "stay" is also displayed. See if you can eliminate that.

Thanks!

**Comment by PatrickCoteWurzler** [comment]
Hey Mitch,

I made both of those changes. Let me know what you think!

**Review by iammattwalsh — APPROVED** [review]
Nice work, thank you for the updates!

**Pull request merged**
