### PR TITLE
Jen/python/lab03

### PR DESCRIPTION
**Pull request by NSJen**

### CODE REVIEW

**Comment by NSJen** [comment]
Lab 2 has already been reviewed in the proper branch.

**Review by iammattwalsh — APPROVED** [review]
This works great, nice work!

**Comment by burrowdown** [comment]
Hey @NSJen can you remove the duplicate lab 2 from this branch? It's going to cause a merge conflict if we try to add a file that already exists.

**Review by iammattwalsh — APPROVED** [review]
Thank you!

**Pull request merged**
