### PR TITLE
Jordyn/html/lab02

### PR DESCRIPTION
**Pull request by JordynHolder**

### CODE REVIEW

**Comment by chapman311** [comment]
Page looks great! All lab requirements are being met and I think the colors look really good. I also really like the cat's pictures. 

I have to ask if it was an intentional decision to have the 'events' button disappear by using the `display: none` CSS at widths over 900 pixels?

**Review by iammattwalsh — APPROVED** [review]
Looks great, nice work!

**Comment by JordynHolder** [comment]
> 

It was because I didnt want the top bar to get too big. If I knew how I would of changed it instead to a drop down menu so it wouldn't matter but because I don't know that I just opted to hide it at lower resolutions instead.

**Comment by JordynHolder** [comment]
I used max-width which means anything below that specific size is when the CSS is used, so it disappears on smaller sizes than 900 not larger.

**Pull request merged**
