### PR TITLE
lab 12 completed

### PR DESCRIPTION
**Pull request by mileidy1**
hello this is my completed lab 12 if there is anything i need to fix please let me know

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
This still needs some work. Load it up and look at the results when you choose your "read the list" option. Your CSV ingestion isn't grabbing keys/values correctly. See if you can fix that!

**Review by chapman311 — CHANGES_REQUESTED** [review]
This lab still needs work. When I tried to read the list I got:
`Here is your list [{'': "'luffy'"}, {'': "'zoro'"}, {'': "'sanji'"}, {'': "'usopp'"}, {'': "'nami'"}]`

When trying to remove a character from the list I got a `KeyError`.

**Comment by mileidy1** [comment]
I saw that error yesterday and i thought it fixed it because when i tried
it it no longer did it . But for some reason the cvs file will just erase
itself and I can’t figure it out . I thought i did yesterday 🤦🏽‍♀️. Ill
get on that now.

**Review by chapman311 — APPROVED** [review]
Great job. Code works well. Thank you for making the necessary changes.

**Review by iammattwalsh — APPROVED** [review]

**Pull request merged**
