### PR TITLE
add `code/tony`

### PR DESCRIPTION
**Pull request by webavant**
'nuf said!

### CODE REVIEW

**Comment by webavant** [comment]
Don't you *dare* reject my ocelot (and my pull request)! 🤣

**Comment by webavant** [comment]
All kidding aside, I recognize it's bad form to pull request multiple issues (between both the pic and the personal code/ directory). I'll fix it after lunchtime.

**Comment by webavant** [comment]
Removing this PR. Will reopen this PR after lunch.

**Comment by webavant** [comment]
Alright, it's all good now. Only changes are adding `code/tony` and and `code/tony/.gitkeep`.

**Comment by webavant** [comment]
Ok, this is a lot of unnecessary commit history. I'm aware that I can revert commits. I wonder how that would appear in the pull request when I push such changes. I am curious and I may try that.

**Review by pjz987 — APPROVED** [review]

**Pull request merged**
