### PR TITLE
This is Lab04.py Versions 1 and 2

### PR DESCRIPTION
**Pull request by cesrebol**

### CODE REVIEW

**Review by chapman311 — CHANGES_REQUESTED** [review]
Entering 515 returns 'five hundred ten five'.

**Comment by cesrebol** [comment]
@chapman311 Hi Mitch, I have made the changes requested. When you get the chance!

**Review by chapman311 — CHANGES_REQUESTED** [review]
Entering 0 in the command line returns 'TEN'. Please test throughouly before submitting.

Also, please only submit the branch with a file for version 1 and a file for version 2. No need to name a file 'revised', it only adds confusion.

**Review by chapman311 — APPROVED** [review]
Code looks great. Thank you for making the changes requested. I really like the ALL CAPS output, it leaves no room for misinterpretation.

**Pull request merged**
