### PR TITLE
lab 1

### PR DESCRIPTION
**Pull request by Krystah**
Please pull lab.

### CODE REVIEW

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Please check the instructions on version 4 of this lab, specifically this part:

> But instead of filling out that matrix, and checking for each pair of units (if from_units == 'mi' and to_units == 'km'), we can just convert any unit to meters, then convert the distance in meters to any other unit.

After you change that, double check your output. When I tested I got some unexpected results!

**Review by iammattwalsh — CHANGES_REQUESTED** [review]
Nice work updating how this does the conversion! You're very close, but run it a few times with familiar conversions (e.g. 1yd = 3ft, or 1ft = 12in) and check your code's output.

**Comment by Krystah** [comment]
@MattDWalsh I fixed the lab and merge issue. Thanks for the help!

**Review by iammattwalsh — APPROVED** [review]
Nice work, thanks for the update!

**Pull request merged**
